[package]
name = "gtk_layer_project"
version = "0.1.0"
edition = "2024"

[dependencies]
gtk-layer-shell = { version = "0.5.0", package = "gtk4-layer-shell"}
gtk = { version = "0.9.6", package = "gtk4"}
serde = { version = "*", features = ["derive"] }
serde_json = { version = "*" }
